FROM maven:3.5.4-jdk-8-slim
ENV TASK_DIR="/root/project/task18"
WORKDIR $TASK_DIR
COPY ./ $TASK_DIR/
RUN mvn package

WORKDIR "/root/project"
RUN cp /root/project/task18/target/*.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]